# version : API版本目前支持4.0
jumpserver:
  version: 4.0
  url: https://jms.ops.yangege.cn
  user: admin
  password: ENC(rpmkDYGobkaAqjNM2E+sg9C0F6J1Egf229Jzdj2HeSzMqKR55Flzl/ExPTFJ94ON)
  coco: oc.ops.yangege.cn

# jdbc:mysql://rm-bp1x04709pb2t44p4vo.mysql.rds.aliyuncs.com:3306/jumpserver
