# version : API版本目前支持 1.5.6
jumpserver:
  version: 1.5.6
  url: https://jms.ops.yangege.cn
  user: admin
  password: ENC(rpmkDYGobkaAqjNM2E+sg9C0F6J1Egf229Jzdj2HeSzMqKR55Flzl/ExPTFJ94ON)
  coco: oc.ops.yangege.cn
