# Macbook 安装ansible
# brew install ansible [or] brew upgrade ansible
# 当前最新版本为 ansible 2.9.6_1

ansible:
  version: 2.9.6
  bin: /usr/local/bin/ansible
  dataPath: /Users/liangjian/Documents/workspace/opscloud-data/ansible
  playbookBin: /usr/local/bin/ansible-playbook
  logPath: /logs/ansible/


#   inventoryPath: ${dataPath}/inventory
#   scriptPath: ${dataPath}/script
#   playbookPath: ${dataPath}/playbook